image: archlinux:latest

before_script:
  - pacman -Syu --needed --noconfirm make clang gcc git python{,-pytest,-pylint} llvm ruby cmake rust
  - git submodule update --init
  - cargo install --path submodules/conftool -j$(nproc)
  - export PATH="$HOME/.cargo/bin:$PATH"
  - conftool generate defconfig
  - conftool set CONFIG_FUZZ_TIME 10
  - conftool set CONFIG_FUZZ_LENGTH 32768
  - conftool set CONFIG_FUZZ_TIMEOUT 10

stages:
  - build
  - test
  - fuzz
  - lint

build_lib:
  stage: build
  script:
    - make -j$(nproc)

check:
  stage: test
  script:
    - make -j$(nproc) check

fuzz_hashmap:
  stage: fuzz
  script:
    - conftool set CONFIG_FUZZ_TARGET hashmap
    - make -j$(nproc) fuzz

fuzz_hashtab:
  stage: fuzz
  script:
    - conftool set CONFIG_FUZZ_TARGET hashtab
    - make -j$(nproc) fuzz

fuzz_rbtree:
  stage: fuzz
  script:
    - conftool set CONFIG_FUZZ_TARGET rbtree
    - make -j$(nproc) fuzz

fuzz_svec:
  stage: fuzz
  script:
    - conftool set CONFIG_FUZZ_TARGET svec
    - make -j$(nproc) fuzz

lint:
  stage: lint
  script:
    - make -j$(nproc) lint
