function (scc_version MAJOR MINOR PATCH)
    set (VERFILE ${CMAKE_CURRENT_SOURCE_DIR}/.version)
    file (STRINGS ${VERFILE} VERSTR)
    while (VERSTR)
        list (POP_FRONT VERSTR COMP)
        string (REPLACE " " ";" COMPLIST ${COMP})
        list (POP_BACK COMPLIST VERNUM)

        if (${COMP} MATCHES "^SCC_MAJOR = [0-9]+$")
            message (INFO " Major version ${VERNUM}")
            set (${MAJOR} ${VERNUM} PARENT_SCOPE)
        elseif(${COMP} MATCHES "^SCC_MINOR = [0-9]+$")
            message (INFO " Minor version ${VERNUM}")
            set (${MINOR} ${VERNUM} PARENT_SCOPE)
        elseif(${COMP} MATCHES "^SCC_PATCH = [0-9]+$")
            message (INFO " Patch version ${VERNUM}")
            set (${PATCH} ${VERNUM} PARENT_SCOPE)
        else()
            message (FATAL_ERROR "Unsupported version entry ${VERSTR}")
        endif()
    endwhile()
endfunction()
