= scc_hashtab
:toc:
:toclevels: 2
:source-highlighter: rouge
:source-language: c
:hide-uri-scheme:

`scc_hashtab` is a generic, flat hash table. Probing is SIMD-optimized on amd64 systems adhering to the System V ABI, provided the processor in question has AVX2 support. The initial table is allocated with static storage duration. Once the load factor outgrows the automatic capacity, the table is moved to the heap.

Note that the default hash function _does_ include potential padding in its calculation. As such, care must be taken that this padding is zeroed when working with structures or unions.

== Types

=== scc_hashtab(type)

Expands to an opaque, fat pointer suitable for representing a hash table storing elements of type `type`.

=== scc_eq

Signature of the function used for equality comparison. Should return `true` if and only if the two elements compare equal

[source]
.Defined as
----
typedef _Bool(*scc_eq)(void const *, void const *);
----

=== scc_hash

Signature of the hash function used by `scc_hashtab`. Given a generic pointer to the data and the size, in bytes, of the latter, it should compute and return the hash of the data as an `unsigned long long`.

[source]
.Defined as
----
typedef unsigned long long(*scc_hash)(void const *data, size_t size)
----

== Construction and Deallocation

=== void *scc_hashtab_init(type, scc_eq eq)

Returns the address of a automatically allocated, empty hash table for storing instances of type `type`. The `eq` parameter is used for equality comparisons. The returned pointer must be assigned to a pointer to `type` and should be passed to `scc_hashtab_free` to ensure any dynamically allocated memory is freed.

Hash tables initialized using `scc_hashtab_init` use the https://en.wikipedia.org/wiki/Fowler-Noll-Vo_hash_function#FNV-1a_hash[FNV-1a Fowler-Noll-Vo hash]. If wanting to specify the hash function manually, use `scc_hashtab_with_hash`.

==== Returns

Address of an empty `scc_hashtab` instance with automatic storage duration. The object is initially allocated in the frame of the calling function.

=== void *scc_hashtab_with_hash(type, scc_eq eq, scc_hash hash)

Like `scc_hashtab_init` but sets the hash function of the returned hash table to `hash` instead of the default FNV-1a.

==== Returns

Address of en empty `scc_hashtab` instance. The object is initially allocated in the frame of the calling function.

=== void scc_hashtab_free(void *hashtab)

Deallocate any memory allocated for `hashtab`. If wanting to reuse the `hashtab` parameter after this call returns, the pointer must be passed to `scc_hashtab_init` or equivalent.
